name: Build, Scan, Pre-Deploy and Deploy

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - recette
  #   types: [opened, synchronize, reopened]

permissions:
  contents: read
  actions: write
  pull-requests: write
  issues: write
  id-token: write
  security-events: write
  packages: write

env:
  # RECETTE_IP: "34.175.206.89"
  # RECETTE_IP: ${{ secrets.RECETTE_IP }}
  CACHE_KEY: ${{ github.sha }}

jobs:

  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    outputs:
      image-tag: ${{ steps.set-output.outputs.image-tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/elgg-app:v9
          no-cache: true
          # cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/elgg-app:v9
          cache-to: type=inline

      - name: Set image tag output
        id: set-output
        run: |
          echo "image-tag=${{ secrets.DOCKERHUB_USERNAME }}/elgg-app:v8" >> $GITHUB_OUTPUT

      # - name: Scan Docker image with Trivy
      #   uses: aquasecurity/trivy-action@0.20.0
      #   with:
      #     image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/elgg-app:v9'
      #     format: 'sarif'
      #     output: 'trivy-results.sarif'

      # - name: Upload Trivy SARIF Report
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: 'trivy-results.sarif'

      # - name: Upload SARIF file as artifact (optional)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: trivy-sarif-report
      #     path: trivy-results.sarif
