name: Lint checks
on: [pull_request]
permissions:
  contents: read
  actions: write
  pull-requests: write
  issues: write
  id-token: write
  security-events: write
  packages: write

jobs:
  php_lint:
    name: Validate composer.json and PHP Coding style
    runs-on: ubuntu-latest
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          extensions: gd,pdo,xml,json,mysqli,pdo_mysql,intl
          tools: composer:v2

      - name: Code checkout
        uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> ${GITHUB_OUTPUT}

      - name: Restore Composer Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer validate
        run: composer validate --no-check-all

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --ansi
          if [ ! -f "vendor/bin/phpcs" ]; then
            echo "::error::PHP CodeSniffer not found. Installing..."
            composer require --dev elgg/sniffs squizlabs/php_codesniffer --prefer-dist --no-progress --ansi
          fi

      - name: Run PHP Code Style checks
        run: |
          vendor/bin/phpcs --version
          # Check only existing directories
          if [ -d "mod" ]; then
            echo "Running PHPCS on mod directory"
            vendor/bin/phpcs --standard=vendor/elgg/sniffs/src/Elgg -sp mod
          else
            echo "::warning::No mod directory found for PHPCS checks"
          fi

  languages_lint:
    name: Validate language files are UTF-8 encoded
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Check encoding of Plugin language files
        run: |
          if [ -d "mod" ]; then
            echo 'Checking language files in mod directory...'
            ! find mod/ -name "*.php" -type f -exec file --mime {} \; | grep -v "charset=utf-8" | grep -v "charset=us-ascii" || exit 1
          else
            echo "No mod directory found for language checks"
          fi
